const produtos = [
	{
		id: 1,
		titulo: "Cheese Torto",
		categoria: "Lanche",
		img: "https://unsplash.com/photos/6XmQV6GccYU/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MjZ8fGZvb2R8ZW58MHwyfHx8MTY2NDM0OTAzNQ&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 29.99,
		destaque: true,
		credito: "https://unsplash.com/photos/6XmQV6GccYU",
	},
	{
		id: 2,
		titulo: "Hot-Dog Tradicional",
		categoria: "Lanche",
		img: "https://unsplash.com/photos/QHBBCyWwD4s/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0NDU4MzU2&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 24.99,
		destaque: false,
		credito: "https://unsplash.com/photos/QHBBCyWwD4s",
	},
	{
		id: 3,
		titulo: "Frango Grelhado e Salada",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/FFu3-WGnas0/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0NDU4NDQ1&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 27.99,
		destaque: false,
		credito: "https://unsplash.com/photos/FFu3-WGnas0",
	},
	{
		id: 4,
		titulo: "Enrolado de Carne e Salada",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/riLJ2t6VEmE/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0NDU4NTI1&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 32.99,
		destaque: false,
		credito: "https://unsplash.com/photos/riLJ2t6VEmE",
	},
	{
		id: 5,
		titulo: "Noodles com Vegetais",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/MGFPFWSZfgM/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MjY1fHxmb29kfGVufDB8Mnx8fDE2NjQ0MjE5OTQ&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 35.99,
		destaque: false,
		credito: "https://unsplash.com/photos/MGFPFWSZfgM",
	},
	{
		id: 6,
		titulo: "Panqueca com Frutas e Mel",
		categoria: "Sobremesa",
		img: "https://unsplash.com/photos/y4K7Ydp2z3Y/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTQwfHxmb29kfGVufDB8Mnx8fDE2NjQzODYzOTA&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 29.99,
		destaque: true,
		credito: "https://unsplash.com/photos/y4K7Ydp2z3Y",
	},
	{
		id: 7,
		titulo: "Barca de Sushi",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/lKk2xzM0YFU/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0NDU4ODY2&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 59.99,
		destaque: false,
		credito: "https://unsplash.com/photos/lKk2xzM0YFU",
	},
	{
		id: 8,
		titulo: "Torta de Morango com Chocolate",
		categoria: "Sobremesa",
		img: "https://unsplash.com/photos/myffvvnqHz4/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8Mjg2fHxmb29kfGVufDB8Mnx8fDE2NjQ0NTg3NzU&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 24.99,
		destaque: false,
		credito: "https://unsplash.com/photos/myffvvnqHz4",
	},
	{
		id: 9,
		titulo: "Lanche Saudável de Frango",
		categoria: "Lanche",
		img: "https://unsplash.com/photos/07RKITgmScQ/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MzAwfHxmb29kfGVufDB8Mnx8fDE2NjQ0NTg3NzU&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 26.99,
		destaque: false,
		credito: "https://unsplash.com/photos/myffvvnqHz4",
	},
	{
		id: 10,
		titulo: "Waffle com Banana e Chocolate",
		categoria: "Sobremesa",
		img: "https://unsplash.com/photos/zgohic2mICA/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MzI3fHxmb29kfGVufDB8Mnx8fDE2NjQ0NTkxMzM&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 29.99,
		destaque: false,
		credito: "https://unsplash.com/photos/zgohic2mICA",
	},
	{
		id: 11,
		titulo: "Torta de Cereja com Creme",
		categoria: "Sobremesa",
		img: "https://unsplash.com/photos/sSLi0wraDmQ/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MzYyfHxmb29kfGVufDB8Mnx8fDE2NjQ0NTkyNDc&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 22.99,
		destaque: false,
		credito: "https://unsplash.com/photos/sSLi0wraDmQ",
	},
	{
		id: 12,
		titulo: "Berinjela com Molho do Chefe",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/14nRRx2C4fg/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MjI4fHxmb29kfGVufDB8Mnx8fDE2NjQzODY1MTM&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 26.99,
		destaque: false,
		credito: "https://unsplash.com/photos/14nRRx2C4fg",
	},
	{
		id: 13,
		titulo: "Bife Australiano",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/c3mFafsFz2w/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MzcwfHxmb29kfGVufDB8Mnx8fDE2NjQ0NTkyNDc&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 36.99,
		destaque: false,
		credito: "https://unsplash.com/photos/c3mFafsFz2w",
	},
	{
		id: 14,
		titulo: "Macarrão com Molho Branco e Brócolis",
		categoria: "Refeição",
		img: "https://unsplash.com/photos/8sUsaEEJFxI/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MzgxfHxmb29kfGVufDB8Mnx8fDE2NjQ0NTkzNjU&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 32.99,
		destaque: true,
		credito: "https://unsplash.com/photos/8sUsaEEJFxI",
	},
	{
		id: 15,
		titulo: "Creme Brulé de Morango",
		categoria: "Sobremesa",
		img: "https://unsplash.com/photos/CmguMl2wYFI/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8Mzk1fHxmb29kfGVufDB8Mnx8fDE2NjQ0NTkzNjU&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 23.99,
		destaque: false,
		credito: "https://unsplash.com/photos/CmguMl2wYFI",
	},
	{
		id: 16,
		titulo: "Gin com Limão",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/J7J0oTps4Lo/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0NDU3NTc5&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 19.99,
		destaque: false,
		credito: "https://unsplash.com/photos/J7J0oTps4Lo",
	},
	{
		id: 17,
		titulo: "Marguerita Blue Frozen",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/ER703TdkO5E/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTh8fGRyaW5rfGVufDB8Mnx8fDE2NjQzODIxMTI&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 19.99,
		destaque: false,
		credito: "https://unsplash.com/photos/ER703TdkO5E",
	},
	{
		id: 18,
		titulo: "Mojito de Limão",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/wyLp_6cKqqs/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0NDU5ODE4&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 19.99,
		destaque: false,
		credito: "https://unsplash.com/photos/wyLp_6cKqqs",
	},
	{
		id: 19,
		titulo: "Smoothie de Limão",
		categoria: "Bebida",
		img: "https://unsplash.com/photos/RWjAFiWFj58/download?force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 23.99,
		destaque: false,
		credito: "https://unsplash.com/photos/RWjAFiWFj58",
	},
	{
		id: 20,
		titulo: "Smoothie de Chocolate e Baunilha",
		categoria: "Bebida",
		img: "https://unsplash.com/photos/DczJXIFg5cU/download?force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 24.99,
		destaque: false,
		credito: "https://unsplash.com/photos/DczJXIFg5cU",
	},
	{
		id: 21,
		titulo: "Smoothie de Kiwi",
		categoria: "Bebida",
		img: "https://unsplash.com/photos/1kJtAIHi3_w/download?force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 22.99,
		destaque: false,
		credito: "https://unsplash.com/photos/1kJtAIHi3_w",
	},
	{
		id: 22,
		titulo: "Coquetel de Cereja",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/DtKrV2K5vq8/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTczfHxkcmlua3xlbnwwfDJ8fHwxNjY0NDYwMzE5&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 29.99,
		destaque: true,
		credito: "https://unsplash.com/photos/DtKrV2K5vq8",
	},
	{
		id: 23,
		titulo: "Café Simples",
		categoria: "Bebida",
		img: "https://unsplash.com/photos/SKoZa7rcLlU/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8NTl8fGNvZmZlZXxlbnwwfDJ8fHwxNjY0NDQ2OTk0&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 9.99,
		destaque: false,
		credito: "https://unsplash.com/photos/SKoZa7rcLlU",
	},
	{
		id: 24,
		titulo: "Panqueca com Manteiga de Amendoim",
		categoria: "Sobremesa",
		img: "https://unsplash.com/photos/ThTXYgIcUOQ/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MjMzfHxmb29kfGVufDB8Mnx8fDE2NjQzODY1MTM&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 16.99,
		destaque: false,
		credito: "https://unsplash.com/photos/ThTXYgIcUOQ",
	},
	{
		id: 25,
		titulo: "Cheese Americano",
		categoria: "Lanche",
		img: "https://unsplash.com/photos/dphM2U1xq0U/download?force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 23.99,
		destaque: false,
		credito: "https://unsplash.com/photos/dphM2U1xq0U",
	},
	{
		id: 26,
		titulo: "Hambúrguer Apimentado",
		categoria: "Lanche",
		img: "https://unsplash.com/photos/W9Nub7ogWJE/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTN8fHNhbmR3aWNofGVufDB8Mnx8fDE2NjQ4MTc3MTY&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 25.99,
		destaque: false,
		credito: "https://unsplash.com/photos/FZ4y_IDUJ6w",
	},
	{
		id: 27,
		titulo: "Cheese Burguer Egg",
		categoria: "Lanche",
		img: "https://unsplash.com/photos/7NYn7YfpaZo/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8Mzd8fHNhbmR3aWNofGVufDB8Mnx8fDE2NjQ4MTc3MjU&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 23.99,
		destaque: false,
		credito: "https://unsplash.com/photos/7NYn7YfpaZo",
	},
	{
		id: 28,
		titulo: "Cerveja Inglesa Wiltshire Gold",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/sUhMjrynw5k/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTB8fGFsY29ob2x8ZW58MHwyfHx8MTY2NDgyMDQxNQ&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 14.99,
		destaque: false,
		credito: "https://unsplash.com/photos/sUhMjrynw5k",
	},
	{
		id: 29,
		titulo: "Batida de Limão com Pera",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/uRxuPT6o0j0/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MjV8fGFsY29ob2x8ZW58MHwyfHx8MTY2NDgyMDQyMQ&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 18.99,
		destaque: false,
		credito: "https://unsplash.com/photos/uRxuPT6o0j0",
	},
	{
		id: 30,
		titulo: "Coquetel Martini",
		categoria: "Bebida Alcoólica",
		img: "https://unsplash.com/photos/bO3NbByK0OM/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8NTJ8fGFsY29ob2x8ZW58MHwyfHx8MTY2NDgyMDYzMg&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 26.99,
		destaque: false,
		credito: "https://unsplash.com/photos/bO3NbByK0OM",
	},
	{
		id: 31,
		titulo: "Coca-Cola Lata",
		categoria: "Bebida",
		img: "https://unsplash.com/photos/nWCmjC7dmdo/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjY0ODIwNzQx&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 4.99,
		destaque: false,
		credito: "https://unsplash.com/photos/nWCmjC7dmdo",
	},
	{
		id: 32,
		titulo: "Chá de Camomila com Leite",
		categoria: "Bebida",
		img: "https://unsplash.com/photos/CiyJOrvwBRM/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MjQzfHxkcmlua3xlbnwwfDJ8fHwxNjY0ODIwOTc1&force=true&w=",
		descricao:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia odio, vero magnam cumque provident assumenda quis sit dolorum corrupti dignissimos.",
		preco: 12.99,
		destaque: false,
		credito: "https://unsplash.com/photos/CiyJOrvwBRM",
	},
];
